- profile_bluesky/startup/instrument/framework/initialize.py
> do not call bluesky.utils.install_kicker()

- profile_bluesky/startup/instrument/devices/huber.py
Works as described by @prjemian.
References #20 (this statement will NOT close that issue _when_ the pull request is merged.)  We don't close that issue yet since there is another step (move the calc into the IOC and create a database that will stop the motors based on the calc).
> Implement suspender in theta/2theta as per issue #20

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/ge_controller.py
Add support for the GE PACE5000 pressure controllers using PVPositioner (like for the lakeshores). This has been tested at the beamline.
> Ge controller

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/scaler.py
- profile_bluesky/startup/instrument/devices/user_calc.py
Reverts APS-4ID-POLAR/ipython-polar#30
> Reverts it all

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/filters.py
- profile_bluesky/startup/instrument/devices/huber.py
Initial setup. Used in an experiment, worked well.
The one remaining question is whether we can add more motors to the `fourc` class. I looked through `hklpy` but didn't figure out if this is really by default.
closes #29
> Diffractometer setup

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/ruby_motors.py
> Ruby motor

- profile_bluesky/startup/instrument/devices/lakeshore336.py
- profile_bluesky/startup/instrument/devices/lakeshore340.py
- profile_bluesky/startup/instrument/devices/lakeshores.py
> Temperature controller

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/apd.py
- profile_bluesky/startup/instrument/devices/cyberstar.py
- profile_bluesky/startup/instrument/devices/flat_mirror.py
- profile_bluesky/startup/instrument/devices/monochromator.py
- profile_bluesky/startup/instrument/devices/ruby_motors.py
- profile_bluesky/startup/instrument/devices/scaler.py
- profile_bluesky/startup/instrument/devices/srs810.py
- profile_bluesky/startup/instrument/devices/srs_amplifiers.py
- profile_bluesky/startup/instrument/devices/toroidal_mirror.py
Adds several devices:
- Detector settings: cyberstar, APD, preamps (closes #17).
- Mono feedback.
- Ruby system laser and led control.
- Lockin amplifier
Also added support for the toroidal and flat mirror standard positions.
> Various devices

- profile_bluesky/startup/instrument/plans/energy_plans.py
This is a bit of a workaround for the mono getting stuck (related to #52). The `moveE` plan will skip the monochromator if the current energy is the same as the target.
The one question is if this is something that would be better addressed in the `mono.energy` settings.
> Mono stuck

- profile_bluesky/startup/instrument/devices/user_calc.py
Add `.SetCountTimePlan` and a dummy `.preset_monitor` to the user calc. This is for compatibility with the `qxscan` plan that controls the time per point in the scan.
> update user_calc for compatibility with qxscan.

- profile_bluesky/startup/instrument/framework/initialize.py
> Fix db subscription to RE.

- profile_bluesky/startup/instrument/devices/lakeshore340.py
- profile_bluesky/startup/instrument/framework/initialize.py
- profile_bluesky/startup/instrument/utils/done_signal.py
Sometimes, the lakeshore 340 setpoint would not updates. This fixes that by adding a check if the put command actually updated the value. See #47.
> Lakeshore setpoint test

- profile_bluesky/startup/instrument/mpl/__init__.py
- profile_bluesky/startup/instrument/mpl/plot_absorption.py
Creates functions for conveniently plotting absorption and XMCD scans
> Absorption plot

- profile_bluesky/startup/instrument/plans/local_preprocessors.py
- profile_bluesky/startup/instrument/plans/local_scans.py
> Fixes after merge

- profile_bluesky/startup/instrument/devices/aps_source.py
- profile_bluesky/startup/instrument/devices/kepko.py
- profile_bluesky/startup/instrument/devices/xspress.py
- profile_bluesky/startup/instrument/plans/local_scans.py
- profile_bluesky/startup/instrument/utils/load_vortex.py
These are the changes that were implemented during the last beamtime (Mar 2-8/2021), mostly bug fixes. Fix #93.
> Beamline tweaks

- profile_bluesky/startup/instrument/devices/huber.py
- profile_bluesky/startup/instrument/devices/phaseplates.py
- profile_bluesky/startup/instrument/devices/qxscan_setup.py
Besides __repr__ and __str__, creates __call__ in qxscan_params. Closes #106, related to #81.
> Create __repr__ and __str__ in pr_setup and qxscan_params

- profile_bluesky/startup/instrument/devices/huber.py
- profile_bluesky/startup/instrument/plans/local_scans.py
Adds "fixq" option to all plans that will keep the (HKL) constant during an energy scan (or any scan really...).
Closes #92.
> Create fixQ plan

- profile_bluesky/startup/instrument/devices/util_components.py
`Kind` changing from "normal" to "config".
> Change tolerance and done kind in `PVPositionerSoftDone`

- profile_bluesky/startup/instrument/devices/phaseplates.py
- profile_bluesky/startup/instrument/devices/util_components.py
Slight change to how the `tolerance` works in `PVPositionerSoftDone`
> PVPositionerSoftDone tweak

- profile_bluesky/startup/instrument/devices/__init__.py
- profile_bluesky/startup/instrument/devices/nanopositioner.py
- profile_bluesky/startup/instrument/plans/local_scans.py
@strempfer implemented this at the beamline (using the add_eiger as a base), and I checked it out as a new branch so that we can keep track of it.
It was tested, and it looks good!
> Add nanopositioner motors

- profile_bluesky/startup/instrument/devices/monochromator.py
- profile_bluesky/startup/instrument/devices/util_components.py
Realize one last issue with the implementation. The fix actually made the code a bit simpler.  @prjemian : I think this is ready for `apstools`.
> Tweak PVPositionerSoftDone and convert monochromator to PVPositioner

- profile_bluesky/startup/instrument/devices/ad_eiger.py
- profile_bluesky/startup/instrument/framework/eiger_handler.py
- profile_bluesky/startup/instrument/utils/load_eiger.py
Add another type of trigger to Eiger.
> Eiger trigger

- profile_bluesky/startup/instrument/devices/ad_lambda.py
- profile_bluesky/startup/instrument/devices/phaseplates.py
- profile_bluesky/startup/instrument/framework/initialize.py
- profile_bluesky/startup/instrument/framework/lambda_handler.py
- profile_bluesky/startup/instrument/plans/local_scans.py
- profile_bluesky/startup/instrument/utils/__init__.py
- profile_bluesky/startup/instrument/utils/load_lambda.py
- Add support for the Lambda 250k area detector, including the databroker handler.
- Switch the localDC in phase plates pzt to be a `PvPositionerSoftDone`.
- Adds the local `count` plan.
> AD Lambda plus tweaks

- profile_bluesky/startup/instrument/devices/_mca.py
- profile_bluesky/startup/instrument/devices/vortex_dxp.py
- profile_bluesky/startup/instrument/framework/initialize.py
- profile_bluesky/startup/instrument/mpl/plot_absorption.py
- profile_bluesky/startup/instrument/plans/local_scans.py
- profile_bluesky/startup/instrument/utils/load_vortex.py
Adds support for the Vortex Saturn electronic
> Vortex saturn

- profile_bluesky/startup/instrument/devices/lakeshore336.py
Fixed a bug in the local setup of the Lakeshore 336.
> Lakeshore 336 bug

- profile_bluesky/startup/instrument/devices/shutters.py
- profile_bluesky/startup/instrument/plans/__init__.py
- profile_bluesky/startup/instrument/plans/local_preprocessors.py
- profile_bluesky/startup/instrument/plans/open_shutter.py
Plans to open shutters.
Close #147.
> Create shopen and shclose plans

- profile_bluesky/startup/instrument/devices/high_field_magnet.py
- profile_bluesky/startup/instrument/plans/local_preprocessors.py
+ Fixes #141.
+ Fixes #138.
+ Checks the epics update rate. Changes it to 1 second if > 1 second.
> Updates to 6T magnet

- profile_bluesky/startup/instrument/devices/lakeshore336.py
> Fix lakeshore336 bugs

- environment_files/environment_2022_10.yml
> Updated 2022_10 environment

- profile_bluesky/startup/instrument/devices/lakeshore336.py
It would get stuck if sent to the same position.
> Fix lakeshore336 motion

- profile_bluesky/startup/instrument/devices/high_field_magnet.py
The magnet status is not a good indicator of being "done" because it updates every second...
Fix #164
> Change magnet to PVPositionerSoftDone

- profile_bluesky/startup/instrument/devices/lakeshore336.py
> Lakeshore bug
